from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
from typing import Any
from urllib import error, parse, request


class GitHubError(RuntimeError):
    pass


@dataclass(frozen=True)
class GitHubContext:
    token: str
    repository: str
    pull_request_number: int
    api_url: str = "https://api.github.com"

    @classmethod
    def from_env(cls) -> "GitHubContext":
        token = os.environ.get("GITHUB_TOKEN", "").strip()
        repository = os.environ.get("GITHUB_REPOSITORY", "").strip()
        event_path = os.environ.get("GITHUB_EVENT_PATH", "").strip()
        api_url = os.environ.get("GITHUB_API_URL", "https://api.github.com").strip().rstrip("/")
        missing = [
            name
            for name, value in (
                ("GITHUB_TOKEN", token),
                ("GITHUB_REPOSITORY", repository),
                ("GITHUB_EVENT_PATH", event_path),
            )
            if not value
        ]
        if missing:
            raise GitHubError(f"Missing required environment variable(s): {', '.join(missing)}")

        event = json.loads(Path(event_path).read_text(encoding="utf-8"))
        pull_request = event.get("pull_request") or {}
        number = pull_request.get("number")
        if not isinstance(number, int):
            raise GitHubError("GitHub event did not include pull_request.number.")

        return cls(token=token, repository=repository, pull_request_number=number, api_url=api_url)


@dataclass(frozen=True)
class GitHubPullRequestCommenter:
    context: GitHubContext

    def publish(self, marker: str, body: str) -> str:
        existing = self._find_existing_comment(marker)
        comment_body = f"{marker}\n\n{body.strip()}\n"
        if existing:
            self._request("PATCH", existing["url"], {"body": comment_body})
            return "updated"
        self._request("POST", self._comments_url(), {"body": comment_body})
        return "created"

    def _find_existing_comment(self, marker: str) -> dict[str, Any] | None:
        page = 1
        while True:
            url = f"{self._comments_url()}?{parse.urlencode({'per_page': 100, 'page': page})}"
            comments = self._request("GET", url)
            if not comments:
                return None
            for comment in comments:
                if marker in str(comment.get("body", "")):
                    return comment
            page += 1

    def _comments_url(self) -> str:
        return f"{self.context.api_url}/repos/{self.context.repository}/issues/{self.context.pull_request_number}/comments"

    def _request(self, method: str, url: str, payload: dict[str, Any] | None = None) -> Any:
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        req = request.Request(
            url=url,
            data=data,
            method=method,
            headers={
                "Authorization": f"Bearer {self.context.token}",
                "Accept": "application/vnd.github+json",
                "Content-Type": "application/json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        try:
            with request.urlopen(req, timeout=30) as response:
                content = response.read().decode("utf-8")
                return json.loads(content) if content else None
        except error.HTTPError as exc:
            details = exc.read().decode("utf-8", errors="replace")
            raise GitHubError(f"GitHub HTTP {exc.code}: {details}") from exc
        except error.URLError as exc:
            raise GitHubError(f"GitHub request failed: {exc.reason}") from exc
        except json.JSONDecodeError as exc:
            raise GitHubError("GitHub response was not valid JSON.") from exc


def build_review_comment(mode: str, output_path: Path, body: str) -> tuple[str, str]:
    title = _mode_title(mode)
    marker = f"<!-- code-review-agent:{mode} -->"
    comment = "\n".join(
        [
            f"## {title}",
            "",
            body.strip(),
            "",
            "---",
            f"Generated by `code-review-agent` from `{output_path}`.",
        ]
    )
    return marker, comment


def _mode_title(mode: str) -> str:
    titles = {
        "code-rules": "Code Rules Review",
        "business-rules": "Business Rules Review",
        "aggregate": "Aggregated Code Review",
    }
    return titles.get(mode, "Code Review")
